# Generated by Django 3.2.3 on 2021-06-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.IntegerField()),
                ('lng', models.IntegerField()),
                ('addr', models.CharField(max_length=50)),
                ('reset', models.CharField(max_length=50)),
                ('pet_cnt', models.IntegerField()),
                ('pp_cnt', models.IntegerField()),
                ('ps_cnt', models.IntegerField()),
                ('total_cnt', models.IntegerField()),
            ],
            options={
                'db_table': 'machine',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AdminTable',
        ),
    ]
